# Bridge definitions configuration file
# ----
#
# Format:
#
# [[groups]]
# kind = <string> [foot | cycle | motor_vehicle | vessel]: group kind
# id = <int> (default = 1) [1..n]: group id
# special = <boolean> (default = false): group that needs special treament
#
#   [[groups.components]]
#   kind = <string> [light | sensor]: component kind
#   id = <int> (default = 1) [1..n]: component id
#   distance = <int> (default = 0) [0..n]: only on sensors, distance from light.


# Bridge

# Bridge
# ----

[[groups]]
kind = "bridge"
id = 1

  [[groups.components]]
  kind = "light"
  id = 1
  initial_state = 2

  [[groups.components]]
  kind = "sensor"
  id = 1

  [[groups.components]]
  kind = "gate"
  id = 1

  [[groups.components]]
  kind = "gate"
  id = 2

  [[groups.components]]
  kind = "deck"
  id = 1
  initial_state = 1

# Vessel
# ----

[[groups]]
kind = "vessel"
id = 1

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1

[[groups]]
kind = "vessel"
id = 2

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1

[[groups]]
kind = "vessel"
id = 3

  [[groups.components]]
  kind = "sensor"
  id = 1
