# Traffic lights definitions configuration file
# ----
#
# Format:
#
# [[groups]]
# kind = <string> [foot | cycle | motor_vehicle | vessel]: group kind
# id = <int> (default = 1) [1..n]: group id
# special = <boolean> (default = false): group that needs special treament
# can_be_blocked = <boolean> (default = false): group that is blockable when there is a lot of traffic.
#
#   [[groups.components]]
#   kind = <string> [light | sensor]: component kind
#   id = <int> (default = 1) [1..n]: component id
#   distance = <int> (default = 0) [0..n]: only on sensors, distance from light.

# Foot
# ----

# Foot - North side

[[groups]]
kind = "foot"
id = 1

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

[[groups]]
kind = "foot"
id = 2

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

# Foot - East side

[[groups]]
kind = "foot"
id = 3

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

[[groups]]
kind = "foot"
id = 4

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

# Foot - South side

[[groups]]
kind = "foot"
id = 5

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

[[groups]]
kind = "foot"
id = 6

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

# Foot - West side

[[groups]]
kind = "foot"
id = 7

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

[[groups]]
kind = "foot"
id = 8

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 0

# Cycle
# ----

# Cycle - North side

[[groups]]
kind = "cycle"
id = 1

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

# Cycle - East side

[[groups]]
kind = "cycle"
id = 2

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

# Cycle - South side

[[groups]]
kind = "cycle"
id = 3

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

# Cycle - West side

[[groups]]
kind = "cycle"
id = 4

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

# Motor vehicle
# ----

# MV - North side

[[groups]]
kind = "motor_vehicle"
id = 1

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

[[groups]]
kind = "motor_vehicle"
id = 2

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

[[groups]]
kind = "motor_vehicle"
id = 3
can_be_blocked = true

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

# MV - East side

[[groups]]
kind = "motor_vehicle"
id = 4

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

[[groups]]
kind = "motor_vehicle"
id = 5

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

  [[groups.components]]
  kind = "sensor"
  id = 4
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 5
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 6
  distance = 2

[[groups]]
kind = "motor_vehicle"
id = 6

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

# MV - South side

[[groups]]
kind = "motor_vehicle"
id = 7
can_be_blocked = true

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 4
  distance = 1

[[groups]]
kind = "motor_vehicle"
id = 8

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

# MV - East side

[[groups]]
kind = "motor_vehicle"
id = 9

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

[[groups]]
kind = "motor_vehicle"
id = 10
can_be_blocked = true

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "light"
  id = 2

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

  [[groups.components]]
  kind = "sensor"
  id = 4
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 5
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 6
  distance = 2

[[groups]]
kind = "motor_vehicle"
id = 11

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0

  [[groups.components]]
  kind = "sensor"
  id = 2
  distance = 1

  [[groups.components]]
  kind = "sensor"
  id = 3
  distance = 2

# MV - Special

[[groups]]
kind = "motor_vehicle"
id = 12

  [[groups.components]]
  kind = "light"
  id = 1

  [[groups.components]]
  kind = "sensor"
  id = 1
  distance = 0
